coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0.2%
        base: auto
        flags:
          - unit
        paths:
          - "micro21cm"
       # advanced settings
        branches:
          - main
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
